PlataformaDeCursos/Cursos/urls.py
from django.urls import path
from Cursos.views import login_redirect
from . import views

urlpatterns = [
    # path('', views.vistaInicial, name='inicio'),
    # vista inicial, tabla de cursos
    path('', views.lista_cursos, name='lista_cursos'),
    # vista de detalle de cada curso
    path("curso/<int:curso_id>/", views.detalle_curso, name="detalle_curso"),
    # vista para la inscripción a un curso
    path('curso/<int:curso_id>/inscribirse/', views.inscribirse_curso, name='inscribirse_curso'),
     # vista para el registro de un usuario
    path('registro/', views.registro_usuario, name='registro_usuario'), 
    # vista para subir material extra a un curso
    path('curso/<int:curso_id>/subir_material_extra/', views.subir_material_extra, name='subir_material_extra'),
    # vista del progreso de todos los cursos
    path('progreso/', views.progreso_estudiante, name='progreso_estudiante'),
    # vista para ver el recurso
    path('recurso/<int:recurso_id>/', views.ver_recurso, name='ver_recurso'),
    # vista para ver el recurso "completar"
    path('recurso/<int:recurso_id>/completar/', views.marcar_completado, name='marcar_completado'),
    # vista para ver el maestro"
    path('dashboard/', views.dashboard, name='dashboard'),
    # vista para la redireccion entre estudiante y maestro"
    path('redireccion/', login_redirect, name='login_redirect'),
    # vista para darse de baja de la materia inscrita
    path('curso/<int:curso_id>/baja/', views.darse_de_baja_curso, name='darse_de_baja_curso'),
    # vista para perfil de usuario
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    # editar la informacion del usuario
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    # cambiar la contraseña del usuario
    path('cambiar-password/', views.cambio_password, name='cambio_password'),
    # eliminar material_extra
    path('material/<int:material_id>/eliminar/', views.eliminar_material_extra, name='eliminar_material_extra'),
    # nueva sesion por curso
    path('crear_sesion/', views.crear_sesion, name='crear_sesion'),
    # Toma asistencia
    path('asistencia/<int:id_sesion>', views.tomar_asistencia, name='tomar_asistencia'),
    # certificado
    path('certificado/<int:user>', views.certificado, name='certificado'),
    # lista sesiones
    path('lista_sesiones/', views.lista_sesion, name='lista_sesiones')
]

PlataformaDeCursos/PlataformaDeCursos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Cursos.urls')),  # urls de la app cursos la unica app
    path('accounts/', include('django.contrib.auth.urls')), #urls de el login/logout para la pagina
]
# Para archivos de multimedia
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PlataformaDeCursos/Cursos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
  #  ---- MODELOS DE LA APLICACION ----
from django.db import models

class Profesor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #Relacion de usuario para que el maestro tenga una sesion igual al estudiante
    nombre = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    especialidad = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Curso(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    profesor = models.ForeignKey(Profesor, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

class Inscripcion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) 
    nombre_estudiante = models.CharField(max_length=100)
    email_estudiante = models.EmailField()
    fecha_inscripcion = models.DateField(auto_now_add=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username if self.user else self.nombre_estudiante} - {self.curso.titulo}"
    
    def porcentaje_asistencia(self):
        total_sesiones = self.curso.sesiones.count()
        asistencias = Asistencia.objects.filter(inscripcion=self, presente=True).count()
        if total_sesiones == 0:
            return 0
        return (asistencias * 100) / total_sesiones
    
    def tiene_certificado(self, minimo=80):
        return self.porcentaje_asistencia() >= minimo

class Recurso(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    tipo_archivo = models.CharField(max_length=50)
    enlace = models.URLField()
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

class Progreso(models.Model):
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE)
    recurso = models.ForeignKey(Recurso, on_delete=models.CASCADE)
    completado = models.BooleanField(default=False)
    fecha_completado = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.inscripcion.nombre_estudiante} - {self.recurso.titulo}"

 # Modelo para el material extra de los cursos
class MaterialExtra(models.Model):
    profesor = models.ForeignKey(Profesor, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100) 
    descripcion = models.TextField(blank=True)
    archivo = models.FileField(upload_to='materiales/')
    fecha_subida = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo
    
# Modelo para un perfil mas profesional del profesor o estudiante
class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='static/perfiles/', default='static/perfiles/perfil_defecto.jpg')
    biografia = models.TextField(blank=True, null=True)
    idioma_nativo = models.CharField(max_length=50, blank=True, null=True)
    intereses = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"

class Sesion(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, related_name='sesiones')
    titulo = models.CharField(max_length=200)
    fecha = models.DateField()
    def __str__(self):
        return f"{self.titulo} - {self.curso.titulo}"
    
class Asistencia(models.Model):
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE)
    sesion = models.ForeignKey(Sesion, on_delete=models.CASCADE)
    presente = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.inscripcion.nombre_estudiante} - {self.sesion.titulo}"
    
class Certificado(models.Model):
    inscripcion = models.OneToOneField(Inscripcion, on_delete=models.CASCADE)
    porcentaje_asistencia = models.FloatField()
    fecha_emision = models.DateField(auto_now_add=True)
    archivo = models.FileField(upload_to='cetificados/', blank=True, null=True)
    def __str__(self):
        return f"Certificado - {self.inscripcion.nombre_estudiante}"

PlataformaDeCursos/Cursos/views.py
from datetime import date
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from .forms import EditarPerfilForm,InscripcionForm,MaterialExtraForm,PerfilForm,RegistroUsuarioForm, SesionForm
from .models import Curso, Inscripcion, MaterialExtra, Perfil, Profesor, Progreso, Recurso, Asistencia, Sesion

# Create your views here.
# Verifica si el usuario tiene asociado un profesor para inicio de Sesion y redirecciones
@login_required
def login_redirect(request):
    if hasattr(request.user, 'profesor'):
        return redirect('dashboard')
    else:
        return redirect('lista_cursos')

# Lista de los cursos en la pagina principal
def lista_cursos(request):
    cursos = Curso.objects.all()
    cursos_inscritos_ids = []
    
    # Verficia si el usuario ya se encuentra inscrito a la materia
    if request.user.is_authenticated:
        cursos_inscritos_ids = Inscripcion.objects.filter(user=request.user).values_list('curso_id', flat=True)

    return render(request, 'cursos/cursos.html', {
        'cursos': cursos,
        'cursos_inscritos_ids': cursos_inscritos_ids
    })

# muesta a detalles las fehas de inicio y fin como tambien los usuarios inscritos en cada curso

@login_required
def detalle_curso(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    inscripciones = Inscripcion.objects.filter(curso=curso)
    es_profesor = hasattr(request.user, 'profesor')
    
    # verifica si  el usuario inscrito en este curso
    esta_inscrito = Inscripcion.objects.filter(user=request.user, curso=curso).exists() if request.user.is_authenticated else False

    return render(request, 'cursos/detalle_Cursos.html', {
        'curso': curso,
        'inscripciones': inscripciones,
        'es_profesor': es_profesor,
        'esta_inscrito': esta_inscrito
    })


# PRIMER FUNCIONALIDAD IMPLEMENTADA
# Inscripción de un usuario a un curso
# requiriendo el login del usuario
@login_required
def inscribirse_curso(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    user = request.user
    
    # Evita que un profesor se inscriba
    if hasattr(request.user, 'profesor'):
        messages.error(request, "Los profesores no pueden inscribirse.")
        return redirect('lista_cursos')
    
    if request.method == 'POST':
        form = InscripcionForm(request.POST)
        if form.is_valid():
            inscripcion, created = Inscripcion.objects.get_or_create(
                user=user,
                curso=curso,
                defaults={
                    'nombre_estudiante': form.cleaned_data['nombre_estudiante'],
                    'email_estudiante': form.cleaned_data['email_estudiante'],
                }
            )
            messages.success(request, '¡Te has inscrito correctamente al curso!')
            if not created:
                # Si ya existe manda este mensaje de error
                form.add_error(None, 'Ya estás inscrito en este curso.')
            return redirect('detalle_curso', curso_id=curso.id)
    else:
        form = InscripcionForm(initial={
            'nombre_estudiante': user.get_full_name() or user.username,
            'email_estudiante': user.email
        })

    return render(request, 'cursos/inscribirse_curso.html', {
        'curso': curso,
        'form': form
    })
    
# SEGUNDA FUNCIONALIDAD IMPLEMENTADA
# SUBIR UN MATERIAL EXTRA
# requiriendo el loggin solo del maestro encargado de la materia

def subir_material_extra(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    if request.method == 'POST':
        form = MaterialExtraForm(request.POST, request.FILES)
        if form.is_valid():
            material = form.save(commit=False)
            material.curso = curso
            material.profesor = Profesor.objects.get(user=request.user)
            material.save()

            # 🔥 Crear Recurso automáticamente
            Recurso.objects.create(
                titulo=material.titulo,
                descripcion=material.descripcion,
                tipo_archivo="Archivo",
                enlace=material.archivo.url,
                curso=curso
            )

            return redirect('subir_material_extra', curso_id=curso.id)
    else:
        form = MaterialExtraForm()

    material_extra = MaterialExtra.objects.filter(curso=curso)

    return render(request, 'cursos/subir_material_extra.html', {
        'curso': curso,
        'form': form,
        'material_extra': material_extra,
    })
    
# Eliminar material extra
@login_required
def eliminar_material_extra(request, material_id):
    material = get_object_or_404(MaterialExtra, id=material_id)

    if material.profesor.user != request.user:
        return HttpResponseForbidden("No tienes permiso para eliminar este material.")

    curso_id = material.curso.id
    
    Recurso.objects.filter(titulo=material.titulo, curso=material.curso).delete()

    material.archivo.delete()  # Borra el archivo en materiales
    material.delete()  # Borra en la base de datos

    messages.error(request, "Material eliminado correctamente.")
    return redirect('subir_material_extra', curso_id=curso_id)


#  VISTA PARA QUE CUALQUIER USUARIO SE PUEDA INSCRIBIR A UN CURSO (evitar al maestro) 
def registro_usuario(request):
    if request.method == "POST":
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('lista_cursos')
    else:
        form = RegistroUsuarioForm()
    return render(request, "registration/registro.html", {"form": form})


# TERCERA FUNCIONALIDAD IMPLEMENTADA
# progreso del estudiante.
# permite al estudiante completar recursos de materias inscritas y verlos en tiempo real
@login_required
def progreso_estudiante(request):
    usuario = request.user
    inscripciones = Inscripcion.objects.filter(user=usuario)
    
    progresos = Progreso.objects.filter(inscripcion__in=inscripciones).select_related('recurso', 'inscripcion', 'inscripcion__curso')

    progreso_por_curso = {}
    for inscripcion in inscripciones:
        recursos = Recurso.objects.filter(curso=inscripcion.curso)
        completados = progresos.filter(inscripcion=inscripcion, completado=True).count()
        total = recursos.count()
        porcentaje = (completados / total * 100) if total > 0 else 0
        progreso_por_curso[inscripcion.curso.id] = {
            'curso': inscripcion.curso,
            'porcentaje': round(porcentaje, 2),
            'total': total,
            'completados': completados,
            'recursos': recursos,
            'completados_ids': list(progresos.filter(inscripcion=inscripcion, completado=True).values_list('recurso_id', flat=True))
        }
    return render(request, 'cursos/progreso_estudiante.html', {
        'progreso_por_curso': progreso_por_curso
    })

# Ver un recurso ya creado
@login_required
def ver_recurso(request, recurso_id):
    recurso = get_object_or_404(Recurso, id=recurso_id)
    inscripcion = Inscripcion.objects.filter(user=request.user, curso=recurso.curso).first()
    if not inscripcion:
        return HttpResponseForbidden("No estás inscrito en este curso.")

    progreso = Progreso.objects.filter(inscripcion=inscripcion, recurso=recurso).first()
    
    completado = progreso.completado if progreso else False
    return render(request, 'cursos/ver_recurso.html', {
        'recurso': recurso,
        'completado': completado
    })

# Marcar como completado el recurso visto por el estudiante.
@login_required
def marcar_completado(request, recurso_id):
    recurso = get_object_or_404(Recurso, id=recurso_id)
    inscripcion = Inscripcion.objects.filter(user=request.user, curso=recurso.curso).first()
    if not inscripcion:
        return HttpResponseForbidden("No estás inscrito en este curso.")

    progreso, _ = Progreso.objects.get_or_create(inscripcion=inscripcion, recurso=recurso)
    progreso.completado = True
    progreso.fecha_completado = date.today()
    progreso.save()

    return redirect('ver_recurso', recurso_id=recurso.id)

#EXTRAS
#Darse de baja de curso
from django.contrib import messages

@login_required
def darse_de_baja_curso(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    inscripcion = Inscripcion.objects.filter(user=request.user, curso=curso).first()

    if not inscripcion:
        messages.error(request, "No estás inscrito en este curso.")
        return redirect('detalle_curso', curso_id=curso.id)

    if request.method == 'POST':
        inscripcion.delete()
        messages.error(request, f"Tu inscripción ha sido cancelada: {curso.titulo}.")
        return redirect('lista_cursos')

    return render(request, 'cursos/confirmar_baja.html', {'curso': curso})



#maestro vea a sus estudiantes con el progreso
@login_required
def dashboard(request):
    if hasattr(request.user, 'profesor'):
        profesor = request.user.profesor
        cursos = Curso.objects.filter(profesor=profesor)
        cursos_con_inscripciones = []

        for curso in cursos:
            inscripciones = Inscripcion.objects.filter(curso=curso)

            # Para cada inscripción, obtener progreso de ese estudiante en ese curso
            estudiantes_con_progreso = []
            for inscripcion in inscripciones:
                total_recursos = Recurso.objects.filter(curso=curso).count()
                completados = Progreso.objects.filter(inscripcion=inscripcion, completado=True).count()
                porcentaje = (completados / total_recursos * 100) if total_recursos > 0 else 0

                estudiantes_con_progreso.append({
                    'inscripcion': inscripcion,
                    'progreso': round(porcentaje, 2),

PlataformaDeCursos/Cursos/templates/cursos/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilos_generales.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_cursos.css' %}?v=1">
    <link rel="stylesheet" href="{% static 'css/estilos_barraNavegacion.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_login.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_verRecurso.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_editarInformacion.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_panelProfesor.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_perfil_usuario.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_progresoEstudiante.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_detalleCurso.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_inscripcion.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_perfilProfesor.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos_subirMaterialExtra.css' %}">
    <title>{% block title %}Plataforma Cursos{% endblock %}</title>
  </head>
  <body>
    <header class="navbar">
      <div class="navbar-container">
        <h1 class="logo">Plataforma de Cursos</h1>
        <nav class="nav-links">
          {% comment %} Redirige Inicio al panel de control si es profesor o listar cursos si es estudiante {% endcomment %}
          <a href=" {% if user.is_authenticated and user|dictsort:"profesor" %}
                      {% url 'dashboard' %}
                    {% else %}
                      {% url 'lista_cursos' %}
                    {% endif %}">
                    📚 Inicio
          </a>
          {% comment %} Ver listado de cursos si es profesor, el estudiante con el boton Inicio vee el listado {% endcomment %}
          {% if user.is_authenticated %}
            {% if user.profesor %}
              <a href="{% url 'lista_cursos' %}">📖 Ver listado de cursos</a>
            {% endif %}
          {% endif %}
          {% comment %} El profesor no puede ver su progreso dado que no esta inscrito a cursos {% endcomment %}
          {% if user.is_authenticated %}
            {% if not user.profesor %}
              <a href="{% url 'progreso_estudiante' %}">📈 Ver mi progreso</a>
            {% endif %}
          {% endif %}
          <!--CREAR CERTIFICADO-->
          {% if user.username %}
              <a href="{% url 'certificado' user.id %}">Crear Certificado</a>
          {% endif %}
          {% if user.is_authenticated %}
            <a href="{% url 'perfil_usuario' %}" class="perfil-usuario-enlace">
              <span class="welcome-text">👤 {{ user.username }}</span>
            </a>
            <form action="{% url 'logout' %}" method="post" class="logout-form">
              {% csrf_token %}
              <button type="submit">Cerrar sesión</button>
            </form>
          {% else %}
            <a href="{% url 'login' %}">Iniciar sesión</a>
          {% endif %}
        </nav>
      </div>
    </header>

    <div class="contenido">
      {% block content %}{% endblock %}
    </div>
    {% comment %} muestra mensajes en el cambio de user y contra {% endcomment %}
    {% if messages %}
      <div id="popup-message" class="popup-message {% for message in messages %}{{ message.tags }}{% endfor %}">
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>
    {% endif %}
    <script>
      window.addEventListener('DOMContentLoaded', function() {
        var popup = document.getElementById('popup-message');
        if (popup) {
          setTimeout(function() {
            popup.style.opacity = '0';
            setTimeout(function() {
              popup.style.display = 'none';
            }, 500);
          }, 3000); 
        }
      });
    </script>
  </body>
</html>

PlataformaDeCursos/Cursos/templates/cursos/certificado.html
{% extends "cursos/base.html" %}

{% block content %}
  
    <h2>Certificado del Curso</h2>
    {% if porcentaje > 80 %}
        <p><strong>Estudiante:</strong> {{ inscripcion.nombre_estudiante }} </p>
        <p><strong>Curso:</strong> {{ inscripcion.curso.titulo }} </p>
        <p><strong>Asistencia:</strong> {{ porcentaje|floatformat:2 }}% </p>
    {% else %}
        <h3>usted NO tiene un minimo de asistencias para certificado</h3>
    {% endif %}

{% endblock content %}

PlataformaDeCursos/Cursos/templates/cursos/confirmar_baja.html
{% extends 'cursos/base.html' %}

{% block title %} Confirmar baja {% endblock %}

{% block content %}
<h2>Confirmar Abandonar curso: {{ curso.titulo }}</h2>
<p>¿Estás seguro que deseas salir de este curso?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Salir del Curso</button>
    <a href="{% url 'detalle_curso' curso.id %}"><button type="button">Cancelar</button></a>
</form>
{% endblock %}

PlataformaDeCursos/Cursos/templates/cursos/crear_sesion.html
{% extends "cursos/base.html" %}

{% block content %}
  
    <h2>Crear Sesion</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
        <!--<a href=""><button type="button">Cancelar</button></a>-->
    </form>

{% endblock content %}

PlataformaDeCursos/Cursos/templates/cursos/dashboard_profesor.html
{% extends 'cursos/base.html' %}

{% block title %} Panel del Profesor {% endblock %}

{% block content %}
<div class="contenido-panel-profesor">
  <h2 class="titulo-principal">Cursos Impartidos</h2>

  {% for item in cursos_con_inscripciones %}
    <div class="card-curso">
      <div class="cabecera-curso">
        <h3 class="titulo-curso">{{ item.curso.titulo }}</h3>
        <span class="contador-estudiantes">
          👥 {{ item.estudiantes|length }} inscritos
        </span>
      </div>
      <p class="descripcion-curso">{{ item.curso.descripcion }}</p>

      {% if item.estudiantes %}
        <div class="tabla-container">
          <table class="tabla">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Usuario</th>
                <th>Email</th>
                <th>Progreso</th>
                <th>Recursos</th>
              </tr>
            </thead>
            <tbody>
              {% for estudiante in item.estudiantes %}
                <tr>
                  <!--Muestra nombre completo-->
                  <td>
                    {% with estudiante.inscripcion.user as u %}
                      {% if u.first_name or u.last_name %}
                        {{ u.first_name }} {{ u.last_name }}
                      {% else %}
                        {{ estudiante.inscripcion.nombre_estudiante|default:"-" }}
                      {% endif %}
                    {% endwith %}
                  </td>
                  <td>
                    {% if estudiante.inscripcion.user %}
                      {{ estudiante.inscripcion.user.username }}
                    {% else %}
                      -
                    {% endif %}
                  </td>
                  <td>
                    {{ estudiante.inscripcion.email_estudiante }}
                  </td>
                  <td>
                    <div class="barra-progreso_profesor">
                      <div class="barra-progreso-llenado_profesor" data-porcentaje="{{ estudiante.progreso }}">
                        <span class="barra-texto_profesor">{{ estudiante.progreso }}% completado</span>
                      </div>
                    </div>
                  </td>
                  <td>{{ estudiante.completados }} / {{ estudiante.total_recursos }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <p class="texto-inscrito">No hay estudiantes inscritos.</p>
      {% endif %}

      <div class="btn-container">
        <a href="{% url 'subir_material_extra' item.curso.id %}" class="btn-subir">
          📁 Subir Material Extra
        </a>
      </div>
    </div>
  {% empty %}
    <p class="texto-inscrito">No tienes cursos asignados.</p>
  {% endfor %}
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const barras = document.querySelectorAll(".barra-progreso-llenado_profesor");

    barras.forEach(barra => {
      const porcentaje = parseInt(barra.dataset.porcentaje || 0);
      barra.style.width = porcentaje + "%";
    });
  });
</script>

{% endblock %}

PlataformaDeCursos/Cursos/templates/cursos/editar_perfil.html
{% extends 'cursos/base.html' %}

{% block title %}Editar Perfil{% endblock %}

{% block content %}
<div class="editar-perfil-container" style="max-width: 500px; margin: 2rem auto; background: #a5d5f5; border-radius: 10px; box-shadow: 0 2px 8px #0001; padding: 2rem;">
    <h2 style="text-align:center; margin-bottom: 1.5rem;">Editar mi perfil</h2>
    <form method="post" enctype="multipart/form-data" class="form-editar-perfil">
        {% csrf_token %}
        <h3 style="margin-bottom: 1rem;">Información básica</h3>
        {% for field in user_form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
              <small class="help-text">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <div class="error-text">{{ error }}</div>
            {% endfor %}
          </div>
        {% endfor %}


        <h3 style="margin-top: 2rem; margin-bottom: 1rem;">Información profesional</h3>
        {% for field in perfil_form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
              <small class="help-text">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <div class="error-text">{{ error }}</div>
            {% endfor %}
          </div>
        {% endfor %}

        <div style="text-align:center; margin-top: 1.5rem;">
            <button type="submit" class="btn_editar">Guardar cambios</button>
            <a href="{% url 'perfil_usuario' %}" class="btn_editar" style="background:#ccc; color:#333; margin-left:10px;">Cancelar</a>
        </div>
        <div style="text-align:center; margin-top: 1rem;">
            <a href="{% url 'cambio_password' %}">Cambiar contraseña</a>
        </div>
    </form>
</div>
{% endblock %}

PlataformaDeCursos/Cursos/templates/cursos/tomar_asistencia.html
{% extends "cursos/base.html" %}

{% block content %}
  
    <h2>Asistencia - {{ sesion.titulo }} </h2>
    <form action="" method="post">
        {% csrf_token %}
        <table border="1">
            <tr>
                <th>Estudiante</th>
                <th>Presente</th>
            </tr>
            {% for ins in inscripciones %}
            <tr>
                <td> {{ ins.nombre_estudiante }} </td>
                <td>
                    <input type="checkbox" name="presente_{{ ins.id }}" id=""
                    {% if ins.asistencia_set.first.presente %}
                      checked
                    {% endif %}>
                </td>
            </tr>
              
            {% endfor %}
        </table>
        <button type="submit">Guardar Asistencia</button>
    </form>

{% endblock content %}